### ISSUE TITLE
[Data Collection] Create a dataset based on Renewable Energy World Overview

### ISSUE THREAD

**Issue by syovchev** [DataSciencePraktikumTUBerlin/DataCollection#1]
## Issue
Create a dataset based on Renewable Energy World Overview

## Tasks
* pick important data 
* gather data
* clean data
* create a new dataset and save it as a CSV-file

## Data source
https://ourworldindata.org/renewable-energy

## Language
Python

## Assignee
Roberto

**Comment by robmip** [comment]
No sure anymore if i did it this way, but now is surely way to late X)
