### ISSUE TITLE
[Data Collection] Create a dataset with Renewable Energy Stocks

### ISSUE THREAD

**Issue by syovchev** [DataSciencePraktikumTUBerlin/DataCollection#2]
## Issue
Either use the Quandl API or scrape Yahoo Finance in order to create a dataset with the relevant stock price information
## Tasks
* gather data
        a. build scraper
        b. use API
* clean data
* create a separate CSV-file for each company
## Data source
https://www.quandl.com/data/EOD-End-of-Day-US-Stock-Prices
https://finance.yahoo.com/
## Language
Python
## Assignee
Stefan

**Comment by robmip** [comment]
I think here you did perfectly
